### ISSUE TITLE
kbrightness - Failed to connect to AppleLMUController getKeyboardBrightness() error

### ISSUE THREAD

**Issue by spnkr** [pirate/mac-hardware-toys#8] opened 2018-07-19 06:05 UTC
did git clone, and can't get kbrightness to work. it always gives this error

```
Failed to connect to AppleLMUController getKeyboardBrightness() error
```

```
 OS X High Sierra 10.13.4 (17E199) [or is called macOS High Sierra now?]
 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Intel Core i7
  Processor Speed:	3.1 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
  Boot ROM Version:	MBP143.0175.B00
  SMC Version (system):	2.45f0
```

**Comment by pirate** [comment] 2018-07-31 00:54
AFAIK it doesn't work on the new USB-C Macs, only ones with the old SMC controllers.

Feel free to investigate and report back if you can find out why, unfortunately I don't have a new mac to debug/test it on so I cant really help here.

**Comment by ffd8** [comment] 2019-10-21 16:06
Year later.. any updates on testing with MBP w/ touchbar? 
Would love to use, but lack skills to update this...

**Comment by pirate** [comment] 2019-10-21 18:10
I didn't have a touch-bar mac last year and I still don't have one now 😁  Without hardware to test it on I'm afraid I cant do much to try and fix this.

<sup>Until they add an SD card slot back and fix the keyboard, I have no desire to upgrade, my trusty 2014 MBP is still plenty fast ⚡️(with all the ports I need and a nice keyboard).</sup>

**Comment by ffd8** [comment] 2019-10-21 18:19
Yeeeah... but on the other hand, [look at all the fun you'd have with a touchbar?!](https://github.com/erikolsson/Touch-Bar-Lemmings)

**Comment by pirate** [comment] 2019-12-02 18:14
I just got a new mac... the day has finally arrived.

Now I have proper motivation to get this working again 😆

**Comment by pirate** [comment] 2019-12-03 21:56
Closing as duplicate of #1

**Closed as completed by pirate** 2019-12-03 21:56 UTC

**Comment by pirate** [comment] 2026-04-01 09:25
Try now, should be working: https://github.com/pirate/mac-hardware-toys
